# Generated by scripts/update-formula.sh — the update workflow rewrites this
# file whenever a new kanea release is published. Edit the script, not this
# file (kanea PRD §5.2.12, v1.60/v1.67).
#
# Install:
#     brew tap m18h/kanea
#     brew trust m18h/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/m18h/kanea"
  version "0.19.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.19.0/kanea_0.19.0_darwin_arm64.tar.gz"
      sha256 "2c0899f9586e9e3b05637d415361e6fcd8a170a4d2b406e4aaf8e51f7f7174ab"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.19.0/kanea_0.19.0_darwin_amd64.tar.gz"
      sha256 "0f36b4b9674e30cf851188cee2ccfa41e1e96c1b1edcb2871f0130de6d1438e0"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.19.0/kanea_0.19.0_linux_arm64.tar.gz"
      sha256 "ea53aea99213747e8f75b6832a163b3499e76fd45ea5a0f83df225edb9b13a3b"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.19.0/kanea_0.19.0_linux_amd64.tar.gz"
      sha256 "2be11b356269997fa80f1a4e8d1e25a9714a417721dd513df15031d7d315a706"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/m18h/kanea#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
