# Generated by scripts/update-formula.sh — the update workflow rewrites this
# file whenever a new kanea release is published. Edit the script, not this
# file (kanea PRD §5.2.12, v1.60/v1.67).
#
# Install:
#     brew tap m18h/kanea
#     brew trust m18h/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/m18h/kanea"
  version "0.29.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.29.0/kanea_0.29.0_darwin_arm64.tar.gz"
      sha256 "86e15e89e8e5ffedda4e55d2c6bd7ea4d03818ec63e51698f3dd24e8e38ad9bc"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.29.0/kanea_0.29.0_darwin_amd64.tar.gz"
      sha256 "85e7939371f2c52822e369668e4f16d7eb2e3d596f510090025ac37cd60321b4"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.29.0/kanea_0.29.0_linux_arm64.tar.gz"
      sha256 "d7ba6578399c7ba1a65e531d5982fdf05efe66742cad0321dd3587e771db13b6"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.29.0/kanea_0.29.0_linux_amd64.tar.gz"
      sha256 "b9f8f9ccc62a2b3b634cf9880cddf249daba4b61d41d4b120fadd3236994f7ea"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/m18h/kanea#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
