# Generated by scripts/update-formula.sh — the update workflow rewrites this
# file whenever a new kanea release is published. Edit the script, not this
# file (kanea PRD §5.2.12, v1.60/v1.67).
#
# Install:
#     brew tap m18h/kanea
#     brew trust m18h/kanea
#     brew install kanea
class Kanea < Formula
  desc "Container orchestration in one binary"
  homepage "https://github.com/m18h/kanea"
  version "0.35.0"
  license "Apache-2.0"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.35.0/kanea_0.35.0_darwin_arm64.tar.gz"
      sha256 "cebc126c8b7bfe64bff6b591a4ecd199060ddc7f79e4de1aff2e6d539855c597"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.35.0/kanea_0.35.0_darwin_amd64.tar.gz"
      sha256 "4652808cd0d778952de46ac4d695cc1bd3f9632d36ab28968477e4bb29077ccf"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/m18h/kanea/releases/download/v0.35.0/kanea_0.35.0_linux_arm64.tar.gz"
      sha256 "aeaf310aa11bc600d25154742b768152297790282cd1798350a1b32f141171af"
    end
    on_intel do
      url "https://github.com/m18h/kanea/releases/download/v0.35.0/kanea_0.35.0_linux_amd64.tar.gz"
      sha256 "159143702f353af54ce3c4f44784237861f53a3546c885e9a6d6255eff5c7f00"
    end
  end

  def install
    bin.install "kanea"
  end

  def caveats
    <<~EOS
      The platform (kanead, kanea-edge, kanea init) runs on Linux. On macOS
      this is the authoring CLI: kanea plan validates job specs with file and
      line diagnostics before anything touches a node.

      To set up a Linux node: https://github.com/m18h/kanea#install
    EOS
  end

  test do
    assert_match "kanea v#{version}", shell_output("#{bin}/kanea version")

    # A spec that fails validation proves the real parser is in the binary:
    # plan diagnoses before it dials, so no daemon is needed.
    (testpath/"bad.hcl").write <<~HCL
      service "web" {}
    HCL
    output = shell_output("#{bin}/kanea plan #{testpath}/bad.hcl 2>&1", 1)
    assert_match "problem", output
  end
end
